# Generated by Django 4.2.3 on 2023-07-21 13:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileUrl', models.URLField(default='')),
                ('fullName', models.CharField(default='', max_length=255)),
                ('firstName', models.CharField(default='', max_length=255)),
                ('lastName', models.CharField(default='', max_length=255)),
                ('profileImageUrl', models.URLField(default='')),
                ('currentJob', models.CharField(default='', max_length=255)),
                ('connectionDegree', models.IntegerField()),
                ('job', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('sharedConnections', models.IntegerField()),
                ('url', models.URLField(default='')),
                ('name', models.CharField(default='', max_length=255)),
                ('query', models.CharField(default='', max_length=255)),
                ('category', models.CharField(default='', max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('additionalInfo', models.TextField(default='')),
                ('pastJob', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('state_progress', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='MarketingTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(default='', max_length=100)),
                ('open_rate', models.CharField(default='', max_length=100)),
                ('click_rate', models.CharField(default='', max_length=100)),
                ('reply_rate', models.CharField(default='', max_length=100)),
                ('meeting_rate', models.CharField(default='', max_length=100)),
                ('no_response', models.CharField(default='', max_length=100)),
                ('bounce_rate', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(default='', max_length=100)),
                ('logo', models.URLField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCampaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.CharField(default='', max_length=100)),
                ('total_likes', models.CharField(default='', max_length=100)),
                ('percentage_change', models.CharField(default='', max_length=100)),
                ('duration', models.CharField(default='', max_length=100)),
                ('target', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hackrx.target')),
                ('templates', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hackrx.marketingtemplates')),
            ],
        ),
    ]
