# Generated by Django 4.2.3 on 2023-07-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackrx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='category',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leads',
            name='connectionDegree',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leads',
            name='currentJob',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leads',
            name='firstName',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leads',
            name='fullName',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leads',
            name='job',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leads',
            name='lastName',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leads',
            name='location',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leads',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leads',
            name='pastJob',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leads',
            name='query',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leads',
            name='sharedConnections',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='leads',
            name='url',
            field=models.URLField(default='', max_length=300),
        ),
    ]
