# Generated by Django 4.2.3 on 2023-07-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackrx', '0005_leads_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='leads',
            name='state',
        ),
        migrations.AddField(
            model_name='leads',
            name='facebookUrl',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='leads',
            name='twitterUrl',
            field=models.URLField(default=''),
        ),
    ]
