# Generated by Django 4.2.3 on 2023-07-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackrx', '0006_state_remove_leads_state_leads_facebookurl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailedleads',
            old_name='email',
            new_name='professionalEmail1',
        ),
    ]
