# Generated by Django 4.2.3 on 2023-07-21 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackrx', '0010_leads_lead_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingcampaigns',
            name='templates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackrx.marketingtemplates'),
        ),
    ]
