# Generated by Django 4.2.3 on 2023-07-22 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackrx', '0011_alter_marketingcampaigns_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingcampaigns',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingcampaigns',
            name='impressions',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingcampaigns',
            name='percentage_change',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingcampaigns',
            name='target',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='hackrx.target'),
        ),
        migrations.AlterField(
            model_name='marketingcampaigns',
            name='total_likes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingtemplates',
            name='bounce_rate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingtemplates',
            name='click_rate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingtemplates',
            name='meeting_rate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingtemplates',
            name='no_response',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingtemplates',
            name='open_rate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingtemplates',
            name='reply_rate',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingtemplates',
            name='template_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
